### ISSUE TITLE
Issue with (playMusic) command

### ISSUE THREAD

**Issue by landenthemick** [Cornerstone-CJ/virtual-assistant-CJ#1]
### description
 it plays random songs from the song folder (added around 15-20 songs). But once it starts playing, it gets stuck and can't quit
even the listen command doesn't work
**line 241**

`

           elif 'play music' or 'music' or 'song' in query:

            curr_dir = os.path.dirname(os.path.abspath(__file__)) 
            music_dir = os.path.join(curr_dir, "songs/")
            screen = pygame.display.set_mode((500, 500))
            x = os.listdir(music_dir)
            a= " "
            pygame.mixer.init()
            random.shuffle(x)
            print(f"Now playing {x[0]}")
            
            a = music_dir + str(x[0])
            pygame.mixer.music.load(a)
            pygame.mixer.music.play()
            inp = input()
            running = True
            while running: 
                for event in pygame.event.get():
                    if event.type == pygame.QUIT:
                      running = False
            
`

**Comment by algo-1** [comment]
I'll check this out now
